# Generated by Django 4.2.22 on 2026-07-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_courseactivity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="banner",
        ),
    ]
